### PR TITLE
adding Continent

### PR DESCRIPTION
**Pull request by wpdevs**
i believe this is missing continent

### CODE REVIEW

**Comment by g-may** [comment]
Thanks @wpdevs! You're correct. Adding this to the new entity types pages in https://github.com/IBM-Bluemix-Docs/natural-language-understanding/pull/30.

**Comment by wpdevs** [comment]
Hi Garrett - 

Sorry I am writing here but I remembered I had interacted with you on the above issue. 

I'm trying to find out how to add a timeout to my NLP request- the other day it seemed like there was slow service for a moment and my application hung.

I have watson_developer_cloud v1 and was looking for where to add the timeout. Is there a parameter for this in the package?

I saw this answer but could not find a set_http_config in the code.
https://developer.ibm.com/answers/questions/457275/timeout-a-natural-language-understanding-request/

best,
Brad

**Comment by g-may** [comment]
Hey Brad, no problem, thanks for asking 👍 

If you are using the Python SDK you might have to update to the latest version. I think this should cover what you're looking for: https://github.com/watson-developer-cloud/python-sdk#configuring-the-http-client-supported-from-v110.

**Comment by g-may** [comment]
There are docs for previous versions of the Python SDK listed here: http://watson-developer-cloud.github.io/python-sdk/

Looks like `set_http_config` was removed in version 3.0.0 of the SDK

**Comment by wpdevs** [comment]
Thank you so much Garrett  :)  I'll look into it the recommendation.

**Comment by wpdevs** [comment]
Hello Garrett,

Sorry for following up here again but didn't know where better

We have been using the service without disruption since the migration from alchemy to IBM Watson Natural Language.

However, it seems recently -- not sure how recently -- we started to get a 401 unauthorized in response to our API calls.

We've been supplying an NLP_USERNAME, NLP_PASSWORD, NLP_URL (https://gateway.watsonplatform.net/natural-language-understanding/api) and were on  
NLP_VERSION = "2017-02-27"

Are you able to help me out here?  Sorry for the request.

**Pull request closed without merging**
